### PR TITLE
Do not let Squid cache its own cache manager responses

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**
This is a workaround for a newly discovered Squid bug.

### CODE REVIEW

**Review by rousskov — APPROVED** [review]
Thank you!

**Comment by rousskov** [comment]
Please use the adjusted PR title/description for merging these changes.

**Comment by eduard-bagdasaryan** [comment]
Sorry, but I lack permissions to merge this PR manually.

**Comment by rousskov** [comment]
Merged manually at [69d0f6a](https://github.com/measurement-factory/squid-overlord/commit/69d0f6ac4b721ec06e16213ba5d1fe1c7b2d79ae).

**Pull request closed without merging**
